name: rbws
description: really bad web server (another generic http/1.1 server implementation)
version: 3.0.0-pr2
repository: https://github.com/masonfrykman/rbws

topics:
  - http
  - server

environment:
  sdk: ^3.2.0

dependencies:
  mime: ^2.0.0

dev_dependencies:
  archive: ^4.0.7
  lints: ^6.0.0
  test: ^1.25.7

platforms:
  linux:
  macos:
  windows: